name: ifrs16-lbo
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy=1.24
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - pymc=5.7
  - arviz
  - tqdm
  - seaborn
  - pip
  - pip:
      - lifelines
      - statsmodels
      - uv
